### ISSUE TITLE
implement worker statistics

### ISSUE THREAD

**Issue by tomleibo** [tomleibo/distributedSystems#15]
the statistics file of each one of the workers; 1. how many links did it parse 2. how many links were faulty 3. how many links were OK.

**Comment by hagai-lvi** [comment]
Will be implemented in the manager:
- Each worker will create himself a UUID when it starts.
- It will add the UUID to every tweet that it parses
- If the manager will detect an error, it will add an error, otherwise it will add a success

**Comment by hagai-lvi** [comment]
Current implementation:
the manger prints a message:

```
WorkersStatistics{
a210cdb8-027e-45d0-8675-b21c320acbb0:successCount=6, failCount=1
a219cdb8-027e-45d0-8675-b21c320ad64q:successCount=3, failCount=2
}
```

The requirements doesn't specify what should be done with the statistics file, maybe we need to upload to s3?

**Comment by tomleibo** [comment]
It seems like it should document one run and we should submit it with the rest of our code.

**Comment by tomleibo** [comment]
Majid answered by mail saying we should generate one for each run so we can examine it on the frontal checks.

**Comment by hagai-lvi** [comment]
OK, so we need to understand if this is specific to each task (i.e. for each local), or in general, and when should we send it

**Comment by hagai-lvi** [comment]
@tomleibo Currently the manager uploads a statistics file to s3, only after it receives a `terminate` message (i.e. only once per a manager). I think that it is OK, what do you think?

**Comment by hagai-lvi** [comment]
All seems to work fine, though not tested thoroughly.
Required tests:
- More than one `local` - make sure that all the locals finish their operation, make sure that the statistics are correct
- What happens on crashes?
- anything else?

**Comment by tomleibo** [comment]
I think that statistics at termination is sufficient.
If local crashes then no statistics file will be generated :)
If manager crashes - then the local will create a new one.
If a worker crashes - that is a possible scenario that the program should overcome. Is it tested?
