### ISSUE TITLE
Make sure that the visibility timeout of the sqs queues has a reasonable value, and that it is extended when needed

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#28]
including all the queues:
- [x] local to manager
- [x] manager to workers
- [x] workers to manager
- [x] manager to local
- anywhere else?

**Comment by tomleibo** [comment]
Do you think the default 30 seconds is too much or too few?
How much time does a worker usually take?

**Comment by hagai-lvi** [comment]
The first task that a worker takes relatively long (I think that over 30 seconds, though I'm not sure) because it then initialize the ML lib, but then it becomes faster.
But anyway, there is a thread (class `MessageKeepAlive`), that constantly updates the visibility timeout.

What I think we need to do about this issue is to make sure that it is always guaranteed that the correct behaviour will take place, i.e. if a manager or worker crashes, if a task takes really long time etc.
We also need to make sure that we are safe in any place we use a queue, and that we didn't miss any queue.
