### ISSUE TITLE
Should the workers be multithreaded?

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#33]

**Comment by tomleibo** [comment]
Do our machines have multiple CPUs?

**Comment by hagai-lvi** [comment]
We currently use t2small which have only a single CPU, but we might want to change this to use instance type with multiple CPUs. We need to further investigate this according to the goals of the assignment (should be as fast as possible? as money-efficient as possible? something else?)

**Comment by hagai-lvi** [comment]
EC2 has 20 instances limitation #55
So we might want to start machines that are stronger than t2.micro

**Comment by hagai-lvi** [comment]
@tomleibo due to the limitation of 20 instances, what do you think? it seems like we need the workers to be multithreaded...

**Comment by hagai-lvi** [comment]
No, too weak machines
