### ISSUE TITLE
Takes a long time for the local to write the result file

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#34]

**Comment by tomleibo** [comment]
Make sense. In order to not have all answers in memory I append each tweet separately.
Meaning it opens the file O(tweet) times. I'll leave the descriptor opened instead.

**Comment by hagai-lvi** [comment]
Cool
I haven't checked what causes this, I've just noticed it.
I think it also happens for small results, so I thought it might be related to a `sleep` or something, but I'm not sure

**Comment by tomleibo** [comment]
Didn't happen for small results. Takes less than half a second for a few tweets.

**Comment by hagai-lvi** [comment]
OK, so we can close this issue
