### ISSUE TITLE
Who should terminate the manager and when?

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#39]

**Comment by tomleibo** [comment]
Defined in the assignment. only the local when run with the terminate flag?
Or do you mean in the case that it is never turned off?

**Comment by hagai-lvi** [comment]
There is a small issue about it:
`local-1` sends a task **without** the `terminate` flag.
`local-2` sends a task **with** the `terminate` flag.

But the manager first finishes  `local-2`'s task (this might happen, though a little rare)

So `local-2` sees that the manager has finished, and terminates him, before he could reply to `local-1`

What do you think?

Also, we must make sure that all the workers are terminated before terminating the manager.

**Comment by tomleibo** [comment]
I'm not sure that is a problem. local2 will cause a flag in the manager to be true, yet it will first finish his open tasks and after finishing them it will turn off. In the case that local1's tasks haven't been received yet, it will create a new manager with the heartbit.
This made me think of another race condition: heartbit must be stopped before sending termination message to the manager.

**Comment by tomleibo** [comment]
Fixed the issue mentioned in the comment:
https://github.com/tomleibo/distributedSystems/commit/90548a2e7b3f6f893a8799671222472dba9a8511
Commited with wrong issue#

**Comment by hagai-lvi** [comment]
Decided that the manager wil terminate himself when he finishes all the jobs
and also in case of exceptions
