### ISSUE TITLE
Change all while(true) to while(! interrupted)

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#43]

**Comment by tomleibo** [comment]
It is the same as wrapping these loops in a try catch(InterruptedException). Or is it?
Are there any loops not wrapped with try catch?

**Comment by tomleibo** [comment]
@hagai-lvi

**Comment by hagai-lvi** [comment]
I'm actually not sure about this, maybe what you did in the `LocalMachine` is the best option:

``` java
try {
    while (true) {
    ...
    }
}
catch (InterruptedException e) {
    ...
}
```
