### ISSUE TITLE
EC2 has 20 instances limitation

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#55]
We are not allowed to start more than 20 instances, so the manger shouldn't try to start more than 19 workers.
We should make sure that the manager never tries to start more than 19 workers

**Comment by tomleibo** [comment]
We are not allowed by whom? the assignment specification?

**Comment by hagai-lvi** [comment]
No, by EC2, they limit our account to 20 instances (maybe this can be changed)
