### ISSUE TITLE
Termination is not implemented as required

### ISSUE THREAD

**Issue by hagai-lvi** [tomleibo/distributedSystems#56]
from the assignment:
- Checks if a Manager node is active on the EC2 cloud. If it is not, the application will start the manager node.
- Uploads the file to S3.
- Sends a message to an SQS queue, stating the location of the file on S3
- Checks an SQS queue for a message indicating the process is done and the response (the summary file) is available on S3.
- Downloads the summary file from S3, and create an html file representing the results.
- Sends a termination message to the Manager if it was supplied as one of its input arguments.

We on the other hand, send the termination message with the task
@tomleibo what do you think we should do?

**Comment by tomleibo** [comment]
Revert to the initial implementation.
If I remember correctly, we had two different local-to-manager message types. one of them was termination. Then we changed it to one message with termination parameter.

**Comment by hagai-lvi** [comment]
discussed on phone, better not revert because it was untested

**Comment by tomleibo** [comment]
Should we also change the implementation of how the local machine waits for statistics file?

``` java
TweetsToHtmlConverter converter =ManagerToLocalSqsProtocol.parse(msg.getBody());
                    converter.execute(env.outputFileName);
                    if (env.terminate) {
                        // Expect a statistics file
                        String statsFile = downloadStatsFile();
                        if (statsFile != null) {
                            log.info("Stats file located at " + statsFile);
                        }
                        else {
                            log.info("download statistics file failed.");
                        }
                    }
```

**Comment by hagai-lvi** [comment]
Left to do: send the termination message only after the local gets the reply (I think that this is a requirement)
